---
title: '<span class="dark-highlight">OpenAstrocytes</span>'
subtitle: '<span class="dark-highlight">AI-ready dynamic activity from the astrocyte network</span>'

title-block-banner: img/astro-banner.png
author-title: ''
affiliation-title: ''
published-title: 'Latest'
# modified-title: 'Updated'

author:
    - name: Maxine Levesque
      email: maxine@forecast.bio
    #   affiliation: " "

    - name: Kira Poskanzer

    - name: " "

date: 31 October 2025
# date-modified: 31 October 2025

# abstract-title: "TL;DR"
# abstract: |+
#     This is a test

#     Hello, some more.
---

## TL;DR

...


## Background

The human brain is about one-third neurons. But two-thirds of it isn't; and, in recent years, the neuroscience field has become more acutely aware of the incredible importance of the roles played by those other sorts of cells.

One of those other thirds is made up of **astrocytes**---. Astrocytes form a cellular network woven between the neurons, ...


### Astrocyte calcium dynamics
One absolutely crucial 


## Architecture

... Overview ...

### Backbone: Distributed, typed WebDatasets with `atdata`
The OpenAstrocytes dataset is built on [`atdata`](https://github.com/foundation-ac/atdata), an open-source package we're developing at Forecast for distributed, interoperable usage of AI-ready datasets.[The original motivation for `atdata` internally was to have fast infrastructure for putting together our rich, multimodal datasets to speed up the iteration cycle for our R&amp;D; ]{.aside} `atdata` is built on the open [WebDataset](https://github.com/webdataset/webdataset) format, designed for use as a high-performance AI I/O layer.

`atdata` makes it straightforward to understand structured data from remote repositories:

```python
import numpy as np
import matplotlib.pyplot as plt
from style import HouseStyle

import atdata
from openastros.datasets.uncaging import MovieFrame

dataset_url = 'https://research.forecast.bio/datasets/astrocyte_nts-{0000..0024}.tar'

# `atdata` uses generigs to annotate sample types
dataset = atdata.Dataset[MovieFrame]( dataset_url )

# Under the hood, `atdata`take care of downloading, caching, buffering,
# unpacking samples, etc.
for batch in atdata.shuffled( batch_size = 32 ):
    labels = np.array( batch.labels )
    frames = batch.data
    # Just pull the first batch
    break

with HouseStyle() as s:
    plt.figure()
    plt.imshow( frames[0] )
    plt.show()
```

`atdata`'s typing functionality already helps for keeping datasets sane; but, where keeping track of sample types really shines is when we register *mappings* between types:

```python
from atdata.schemas import LabeledImage

@atdata.projection
def project( sample: MovieFrame ) -> LabeledImage:
    return LabeledImage(
        image = sample.data,
        label = sample.label
    )
```

This design enables us, as we're building AI models from a bunch of different sources, to easily aggregate across our diverse hive of WebDatasets across modalities and experiments that are able to be compatibly merged. The full `atdata` ecosystem is architected to go one step further, placing metadata for type schemas of scientific datasets---and the code for these lenses between them---in a public, decentralized repository on [ATProto](https://atproto.com), the protocol layer underlying the [Bluesky](https://bsky.social/about) social network. This allows AI coding agents on data science tasks to automatically leverage domain knowledge of structured semantic relationships to decide what data to pull from for a given task.[More on `atdata` soon---sign up for updates to hear first as we push more features to the public release!]{.aside}


### The data
...


## Demo

...

#### Patch embeddings from off-the-shelf DINOv3
...

#### Fine-tuning an image model on OpenAstrocytes
...


## Looking ahead

...

#### Building on `atdata`
...

#### Loving neurons, too
...

#### A new kind of data
...

 

---

 

#### Notes


::: {.callout-tip appearance="simple" collapse="true"}

## Acknowledgements

We'd like to thank **Dr. Michelle Cahill** and **Dr. Michael Reitman** for 

:::

::: {.callout-warning appearance="simple" collapse="true"}

## AI usage

No language model tools were used to produce any of the code for or writing in this pub.

:::

::: {.callout-note appearance="simple" collapse="true"}

## Copyright notice

Copyright &copy; 2025 Forecast Bio, Inc.

The contents of this article are licensed under the Creative Commons CC-BY license.

:::


#